[package]
name = "aws_parameter_update"
version = "0.2.1"
authors = ["Lane Sawyer <github@lanesawyer.dev>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
log = "0.4.8"
rusoto_core = "0.42"
rusoto_ssm = "0.42"
simple_logger = "1.6.0"
yaml-rust = "0.4"
