[package]
name = "aws_parameter_update"
version = "0.2.2"
authors = ["Lane Sawyer <cratesio@lanesawyer.dev>"]
edition = "2018"
description = "A small tool used to quickly update simple AWS Parameters."
license = "MIT"
repository = "https://github.com/lanesawyer/aws_parameter_update"
documentation = "https://docs.rs/aws_parameter_update"
readme = "README.md"

[dependencies]
clap = "2.33.0"
log = "0.4.8"
rusoto_core = "0.42"
rusoto_ssm = "0.42"
simple_logger = "1.6.0"
yaml-rust = "0.4"
